Repository whereismytree/frontend, pull requests merged in 2024-03, with the labels that each got.

#56 Fix/ 메인페이지 검색기능 api 오류 수정
  src/pages/SearchPage/index.tsx
  src/pages/SearchPage/style.ts
  src/types/apiResponse.ts
Labels: 📬 API, 🐞 BugFix

#57 Feat/메인페이지 api 적용 및 저장기능 구현
  src/components/SaveButton/index.tsx
  src/pages/MainPage/components/TreeInfoCard/index.tsx
  src/pages/MainPage/components/TreeInfoCard/style.ts
  src/pages/MainPage/hooks.ts
  src/pages/MainPage/index.tsx
  src/pages/TreeInfoPage/components/TreeTitle/index.tsx
  src/types/apiResponse.ts
Labels: ✨ Feature, 📬 API

#58 Fix/트리상세 저장 기능 오류 수정
  src/pages/TreeInfoPage/components/TreeTitle/index.tsx
  src/pages/TreeInfoPage/index.tsx
Labels: 📬 API, 🐞 BugFix

#71 Fix/트리 리뷰 등록,수정 개선사항 업데이트
  src/components/SaveButton/index.tsx
  src/components/TreeLocationItem/index.tsx
  src/pages/MainPage/components/TreeInfoCard/index.tsx
  src/pages/ReviewRegistAndEditPage/index.tsx
  src/pages/SearchPage/index.tsx
  src/pages/SearchPage/style.ts
  src/pages/TreeInfoPage/components/TreeDetails/index.tsx
  src/pages/TreeInfoPage/components/TreeTitle/index.tsx
  src/pages/TreeInfoPage/components/VisitorPhotoList/index.tsx
  src/pages/TreeInfoPage/components/VisitorReviewList/index.tsx
  src/pages/TreeInfoPage/index.tsx
Labels: 📬 API, 🐞 BugFix

#76 Fix/트리상세페이지 오류 수정
  src/assets/tree-info-marker.svg
  src/pages/TreeInfoPage/components/VisitorPhotoList/index.tsx
  src/pages/TreeInfoPage/components/VisitorReviewList/index.tsx
  src/pages/TreeInfoPage/components/style.ts
  src/pages/TreeInfoPage/index.tsx
Labels: 🐞 BugFix

#77 Fix/메인페이지 오류 수정
  src/pages/MainPage/components/ZoomControl/style.ts
  src/pages/MainPage/index.tsx
  src/pages/MainPage/style.ts
Labels: 🐞 BugFix

#78 Fix/검색페이지 오류 수정
  src/pages/SearchPage/index.tsx
Labels: 🐞 BugFix

#73 Feat/image 관련 기능 구현 완료
  package-lock.json
  package.json
  src/hooks/usePreviewImage.ts
  src/utils/imageUtils/convertImageFileToUrl.ts
Labels: ✨ Feature

#84 Feat, Fix/리뷰 등록, 수정 페이지 오류 수정
  src/pages/ReviewRegistAndEditPage/components/ReviewForm/index.tsx
  src/pages/ReviewRegistAndEditPage/components/Tag/index.tsx
  src/pages/ReviewRegistAndEditPage/components/Tag/style.ts
  src/pages/ReviewRegistAndEditPage/index.tsx
  src/pages/ReviewRegistAndEditPage/style.ts
  src/types/apiResponse.ts
Labels: ✨ Feature, 🐞 BugFix

#85 fix: 지번주소 표시되지 않는 오류 수정
  src/pages/MainPage/components/TreeInfoCard/index.tsx
  src/pages/TreeInfoPage/components/TreeTitle/index.tsx
  src/pages/TreeInfoPage/index.tsx
Labels: 🐞 BugFix
